use crate::state::{ActionSequence, AppState, Intent, MacroConfig, StateManager};
use serde::Serialize;
use std::sync::Arc;
use tauri::{command, State};
use uuid::Uuid;

/// WR-05: UUID is generated by the backend and returned to the frontend.
/// The client should NOT supply a UUID — any client-side id is overwritten.
#[command]
pub async fn add_macro(
    state: State<'_, StateManager>,
    config: MacroConfig,
) -> Result<Uuid, String> {
    let (tx, rx) = tokio::sync::oneshot::channel();
    state
        .send_intent(Intent::AddMacro(config, tx))
        .await
        .map_err(|e| e.to_string())?;
    rx.await.map_err(|e| e.to_string())
}

#[command]
pub async fn remove_macro(state: State<'_, StateManager>, id: Uuid) -> Result<(), String> {
    state
        .send_intent(Intent::RemoveMacro(id))
        .await
        .map_err(|e| e.to_string())
}

#[command]
pub async fn set_macro_enabled(
    state: State<'_, StateManager>,
    id: Uuid,
    enabled: bool,
) -> Result<(), String> {
    state
        .send_intent(Intent::SetMacroEnabled(id, enabled))
        .await
        .map_err(|e| e.to_string())
}

#[command]
pub async fn set_macro_target_app(
    state: State<'_, StateManager>,
    id: Uuid,
    target_app: Option<String>,
) -> Result<(), String> {
    state
        .send_intent(Intent::SetMacroTargetApp(id, target_app))
        .await
        .map_err(|e| e.to_string())
}

#[command]
pub async fn get_state(state: State<'_, StateManager>) -> Result<AppState, String> {
    let (tx, rx) = tokio::sync::oneshot::channel();
    state
        .send_intent(Intent::GetState(tx))
        .await
        .map_err(|e| e.to_string())?;
    rx.await.map_err(|e| e.to_string())
}

#[command]
pub async fn get_active_app(state: State<'_, StateManager>) -> Result<Option<String>, String> {
    let (tx, rx) = tokio::sync::oneshot::channel();
    state
        .send_intent(Intent::GetState(tx))
        .await
        .map_err(|e| e.to_string())?;
    let app_state = rx.await.map_err(|e| e.to_string())?;
    Ok(app_state.active_app)
}

/// Bind a global hotkey to toggle a specific macro.
/// `keycode`: macOS virtual keycode (e.g. 12 = Q, 0 = A)
/// `modifiers`: raw CGEventFlags bits (e.g. Cmd=0x100000, Shift=0x20000)
#[command]
pub async fn bind_hotkey(
    _state: State<'_, StateManager>,
    _macro_id: Uuid,
    _keycode: u16,
    _modifiers: u64,
) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    {
        use crate::platform::macos::observer::{add_hotkey_binding, HotkeyAction, HotkeyBinding};
        add_hotkey_binding(HotkeyBinding {
            keycode: _keycode,
            modifiers: _modifiers,
            action: HotkeyAction::ToggleMacro(_macro_id),
        });
    }
    Ok(())
}

/// Remove all hotkey bindings for a specific macro.
#[command]
pub async fn unbind_hotkey(_state: State<'_, StateManager>, _macro_id: Uuid) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    {
        use crate::platform::macos::observer::remove_hotkey_bindings_for;
        remove_hotkey_bindings_for(&_macro_id);
    }
    Ok(())
}

// ── Process Picker: RunningApp type and list_running_apps command ─

/// A user-facing running application returned by `list_running_apps`.
/// macOS: `identifier` is the bundle ID (e.g. "com.mojang.minecraft").
/// Windows: `identifier` is the full exe path (e.g. "C:\...\Minecraft.exe").
#[derive(Debug, Clone, Serialize)]
pub struct RunningApp {
    pub display_name: String,
    pub identifier: String,
}

/// List all user-facing running applications for the process picker.
/// Returns name + bundle ID on macOS; name + exe path on Windows.
/// Fetched on picker focus — no server-side caching (D-06).
#[command]
pub async fn list_running_apps() -> Result<Vec<RunningApp>, String> {
    #[cfg(target_os = "macos")]
    {
        return crate::platform::macos::observer::list_running_apps_impl();
    }
    #[cfg(target_os = "windows")]
    {
        return crate::platform::windows::list_running_apps_impl();
    }
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        Ok(vec![])
    }
}

/// Update the trigger key for an existing macro.
/// macOS: the CGEventTap observes keycode via HOTKEY_BINDINGS (managed separately by bind_hotkey).
/// Windows: trigger key is propagated to MACRO_TRIGGER_KEYS via reevaluate_all_macros in StateActor.
#[command]
pub async fn set_macro_trigger_key(
    state: State<'_, StateManager>,
    id: Uuid,
    trigger_key: Option<u16>,
) -> Result<(), String> {
    state
        .send_intent(Intent::SetMacroTriggerKey(id, trigger_key))
        .await
        .map_err(|e| e.to_string())
}

/// Toggle the global engine on/off.
#[command]
pub async fn toggle_engine(state: State<'_, StateManager>) -> Result<(), String> {
    state
        .send_intent(Intent::ToggleEngineHotkey)
        .await
        .map_err(|e| e.to_string())
}

/// Request Accessibility permissions from the OS.
///
/// - Shows the macOS system dialog prompting the user to grant access.
/// - If already trusted, initializes the CGEventTap (idempotent).
/// - Returns `true` if the process currently has Accessibility permissions.
///
/// The SolidJS frontend should call this on launch and display
/// a "Permissions Required" indicator when it returns `false`.
#[command]
pub async fn request_accessibility() -> Result<bool, String> {
    #[cfg(target_os = "macos")]
    {
        let granted = crate::platform::macos::check_accessibility_permissions(true);
        if granted {
            crate::platform::macos::observer::initialize_tap();
        }
        Ok(granted)
    }
    #[cfg(not(target_os = "macos"))]
    {
        // Windows/Linux: no accessibility gate
        Ok(true)
    }
}

/// Silent check: returns current accessibility status without prompting.
///
/// D-03: arms CGEventTap on post-launch grant (idempotent via TAP_INITIALIZED AtomicBool guard).
/// Called by the frontend 3s poll loop — if the user granted access directly in System Settings
/// (without clicking Request Access), the next poll will arm the tap without requiring a restart.
///
/// On macOS, also writes the TCC was-ever-granted sentinel file on every
/// successful grant (COMPAT-05). The flag is idempotent: its existence is
/// the only signal; its content is always `b"1"`.
#[command]
pub async fn check_accessibility(app_handle: tauri::AppHandle) -> Result<bool, String> {
    #[cfg(target_os = "macos")]
    {
        let granted = crate::platform::macos::check_accessibility_permissions(false);
        if granted {
            crate::platform::macos::observer::initialize_tap();
            crate::persistence::write_tcc_granted_flag(&app_handle);
        }
        Ok(granted)
    }
    #[cfg(not(target_os = "macos"))]
    {
        Ok(true)
    }
}

/// Returns true if the was-ever-granted TCC flag exists. Used by the
/// frontend to detect a TCC identity change after a signed-build upgrade.
#[command]
pub async fn get_tcc_identity_status(app_handle: tauri::AppHandle) -> Result<bool, String> {
    Ok(crate::persistence::tcc_granted_flag_exists(&app_handle))
}

/// Silent check: returns current Input Monitoring status without prompting.
///
/// Paired with the 3s accessibility poll in App.tsx. Same dual-platform stub
/// pattern as `check_accessibility` — returns `Ok(true)` on non-macOS because
/// the permission has no equivalent on Windows/Linux.
#[command]
pub async fn check_input_monitoring() -> Result<bool, String> {
    #[cfg(target_os = "macos")]
    {
        Ok(crate::platform::macos::check_input_monitoring())
    }
    #[cfg(not(target_os = "macos"))]
    {
        Ok(true)
    }
}

// ── Task 3.7: ActionSequence IPC Commands ────────────────────────

/// Set the full action sequence for a macro.
/// This replaces any existing sequence and restarts the macro
/// in the scheduler if it's currently active.
///
/// Example payload from frontend:
/// ```json
/// {
///   "id": "uuid...",
///   "sequence": {
///     "steps": [
///       { "SustainedHold": { "input": { "MouseButton": "Right" } } },
///       { "InterleavedInterval": { "input": { "MouseButton": "Left" }, "interval_ms": 650 } }
///     ]
///   }
/// }
/// ```
#[command]
pub async fn set_macro_sequence(
    state: State<'_, StateManager>,
    id: Uuid,
    sequence: ActionSequence,
) -> Result<(), String> {
    state
        .send_intent(Intent::UpdateSequence(id, sequence))
        .await
        .map_err(|e| e.to_string())
}

/// Update the interval for a specific step within a running macro.
/// Allows the frontend to live-tune timing without restarting the macro.
/// `step_index` is 0-based and maps to the ActionSequence step order.
#[command]
pub async fn update_step_interval(
    state: State<'_, StateManager>,
    id: Uuid,
    step_index: usize,
    interval_ms: u64,
) -> Result<(), String> {
    state
        .send_intent(Intent::UpdateStepInterval(id, step_index, interval_ms))
        .await
        .map_err(|e| e.to_string())
}

// ── Task 5.1: Profile Management IPC Commands ────────────────────

/// Save the current macro state as a named profile.
/// If a profile with this name already exists, it is overwritten.
///
/// CR-03: the name is sanitized early so the stored `ProfileData.name` always
/// matches the filename stem.  Two raw names that map to the same sanitized form
/// (e.g. "My Profile" and "My Profile!!!") would silently overwrite each other
/// without this guard; after sanitization they produce the same `safe_name` and
/// the caller gets an accurate on-disk name back.
#[command]
pub async fn save_profile(
    state: State<'_, StateManager>,
    profile_mgr: State<'_, Arc<crate::persistence::ProfileManager>>,
    name: String,
) -> Result<(), String> {
    // Sanitize early so the stored name always matches the filename stem.
    let safe_name = crate::persistence::ProfileManager::sanitize_name(&name);
    if safe_name.is_empty() {
        return Err(
            "Profile name must contain at least one alphanumeric character.".to_string(),
        );
    }

    // Snapshot the current state.
    let (tx, rx) = tokio::sync::oneshot::channel();
    state
        .send_intent(Intent::GetState(tx))
        .await
        .map_err(|e| e.to_string())?;
    let app_state = rx.await.map_err(|e| e.to_string())?;

    let profile = crate::persistence::ProfileData {
        name: safe_name,
        macros: app_state.macros,
        engine_active: app_state.engine_active,
    };

    profile_mgr.save_profile(&profile).await
}

/// Load a named profile, replacing all current macros.
/// Returns the loaded profile data for the frontend to update.
///
/// CR-06: Uses a oneshot channel so the StateActor performs the single disk
/// read and returns `ProfileData` directly — eliminates the double-read that
/// existed when ipc loaded the profile itself and then sent LoadProfile intent.
#[command]
pub async fn load_profile(
    state: State<'_, StateManager>,
    name: String,
) -> Result<crate::persistence::ProfileData, String> {
    let (tx, rx) = tokio::sync::oneshot::channel();
    state
        .send_intent(Intent::LoadProfile(name, tx))
        .await
        .map_err(|e| e.to_string())?;
    rx.await.map_err(|e| e.to_string())?
}

/// Delete a saved profile by name.
///
/// WR-07: Guard against deleting the reserved "Default" profile — it is the
/// auto-save target used by `auto_save_default()` and must always exist.
#[command]
pub async fn delete_profile(
    profile_mgr: State<'_, Arc<crate::persistence::ProfileManager>>,
    name: String,
) -> Result<(), String> {
    if name.eq_ignore_ascii_case("default") {
        return Err("Cannot delete the reserved 'Default' profile.".to_string());
    }
    profile_mgr.delete_profile(&name).await
}

/// List all saved profiles (name + macro count).
#[command]
pub async fn list_profiles(
    profile_mgr: State<'_, Arc<crate::persistence::ProfileManager>>,
) -> Result<Vec<crate::persistence::ProfileSummary>, String> {
    profile_mgr.list_profiles().await
}
